json.set! 'title', "Waste Services API"
json.set! 'description', "A common API for local government waste services."

# json.organizations "#{request.base_url}organizations"
json.services "#{request.base_url}/services"
json.event_types "#{request.base_url}/event_types"
json.events "#{request.base_url}/events"
json.feature_types "#{request.base_url}/feature_types"
json.features "#{request.base_url}/features"
json.sites "#{request.base_url}/sites"
json.tasks "#{request.base_url}/tasks"
